### ISSUE TITLE
Error when running the script recom-sim

### ISSUE THREAD

**Issue by Marvin02860** [salanova-elliott/recom-sim#1]
Hi, 

Thank you for making and sharing the recom-sim script!
I have tried to run it as a test with the input data file you provided, as follows:

_python recom-sim.py input_file.txt 1 --out justfortest.txt_

 and unfortunately I get the following error message:

**Traceback (most recent call last):
  File "recom-sim.py", line 219, in <module>
    pop1_freq = build_matrix(pop1_raw, loc_list)
  File "recom-sim.py", line 102, in build_matrix
    a = sample[i][0:len(sample[i])/2]
TypeError: slice indices must be integers or None or have an __index__ method**

Would you be able to help with this?

Thank you very much :)
Kind regards,
Marvin

**Comment by y-matsuda97** [comment]
The problem is solved by modifying line 102 and 103 as follows.
```
a = sample[i][0:int(len(sample[i])/2)]
b = sample[i][int(len(sample[i])/2):len(sample[i])]
```
